spring:
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # localhost 금지
    url: jdbc:mysql://seb41-main-036.cofrzunhrbrs.ap-northeast-2.rds.amazonaws.com:3306/pikcha36?serverTimezone=Asia/Seoul # 포트넘버, 스키마이름
    username: admin # 유저네임
    password: ${RDS_PASSWORD} # 비밀번호

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

server:
  servlet:
    encoding:
      force-response: true

mail:
  address:
    admin: admin@gmail.com

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 420
  refresh-token-expiration-minutes: 420

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
    credentials:
      accesskey: ${S3_ACCESS_KEY}
      secretkey: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false