spring:
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  batch:
    job:
      enabled: false # spring 실행시 배치 자동실행 끄기

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # localhost 금지
    url: jdbc:mysql://seb41-main-036.cofrzunhrbrs.ap-northeast-2.rds.amazonaws.com:3306/pikcha36?serverTimezone=Asia/Seoul # 포트넘버, 스키마이름
    username: admin # 유저네임
    password: ${RDS_PASSWORD} # 비밀번호

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://pikcha36.o-r.kr:8080/login/oauth2/code/kakao
            #            redirect-uri: http://localhost:8080
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG


server:
  servlet:
    encoding:
      force-response: true
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: ${SSL_PASSWORD}

mail:
  address:
    admin: admin@gmail.com

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
    credentials:
      accesskey: ${S3_ACCESS_KEY}
      secretkey: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false