spring:
  main:
    allow-circular-references: true

  servlet:
    multipart:
      max-file-size: 2MB  # 2MB 제한
      max-request-size: 2MB # 2MB 제한
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pikcha36?serverTimezone=Asia/Seoul # 포트넘버, 스키마이름
    username: admin # 유저네임
    password: ${RDS_PASSWORD} # 비밀번호

  #  sql:
  #    init:
  #      mode: always
  #      data-locations: classpath*:db/h2/data.sql
  jpa:
    hibernate:
      ddl-auto: none  # If deploy server, have to change please
    #    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://pikcha36.o-r.kr:8080/login/oauth2/code/kakao
            #            redirect-uri: http://localhost:8080
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

server:
  servlet:
    encoding:
      force-response: true

mail:
  address:
    admin: admin@gmail.com

jwt:
  secret-key: ${JWT_SECRET_KEY}  # 환경 변수로 설정했음
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 1


cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
    credentials:
      accesskey: ${S3_ACCESS_KEY}
      secretkey: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false